openapi: 3.0.0
info:
  title: ApiBileMo
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000/api/v1'
    description: 'Api for Phones Catalog in B2B'
paths:
  /phones:
    get:
      operationId: 'App\Controller\PhoneController::index'
      responses:
        '200':
          description: 'list of phones'
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Customer:
      properties:
        id:
          type: integer
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        postCode:
          type: integer
        city:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
      type: object
    Phone:
      properties:
        id:
          type: integer
        brand:
          type: string
        model:
          type: string
        price:
          type: integer
        description:
          type: string
      type: object
