openapi: 3.0.0
info:
  title: ApiBileMo
  version: '1.0'
servers:
  -
    url: 'http://127.0.0.1:8000/api/v1'
    description: 'Api for Phones Catalogue in B2B'
paths:
  /phones:
    get:
      operationId: 'App\Controller\PhoneController::index'
      parameters:
        -
          name: page
          in: query
          description: 'page of the catalog'
          required: false
      responses:
        '200':
          description: 'list phones'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Phone'
  '/phones/{id}':
    get:
      operationId: 'App\Controller\PhoneController::show'
      parameters:
        -
          name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'show phone'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Phone'
components:
  schemas:
    Phone:
      properties:
        id:
          type: integer
        brand:
          type: string
        model:
          type: string
        price:
          type: integer
        description:
          type: string
          nullable: true
      type: object
